name: Run Selenium Tests with Allure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Install dependencies and run tests
      run: mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml

    - name: Generate Allure report
      run: |
        mkdir -p allure-results
        mvn allure:report
        mvn allure:serve & sleep 15 && pkill -f "allure serve"

    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven-plugin
